### ISSUE TITLE
How do I insert data to the meta?

### ISSUE THREAD

**Issue by sharenjoy** [appkr/fractal#2]
How do I insert data to the meta?
It will look like this.
```
{
  "data": {}
  "meta": {
    "rules_failed": {
      "firstname": [
        "The firstname field is required."
      ]
    }
  }
}
```
thanks

**Comment by appkr** [comment]
@sharenjoy Hey! 
Now **you can append additional meta** on `respondWithPagination()`, `respondCollection()`, or `respondItem()` methods. Checkout the following:

```
return $this->respondWithPagination(
    Resource::with('manager')->latest()->paginate(25),
    new ResourceTransformer,
    ['foo' => 'bar']
);
```

---

If you just wanted to spit out the validation errors, you can do it. As the [documentation](https://github.com/appkr/fractal#formrequest) says, just by extending `Appkr\Fractal\Request` from `YourFormRequest`, you can deliver below json validation error to the client. And you can format it however you want, with `errorFormat` at `config/fractal.php`.

```
// Request:
// POST http://localhost:8000/api/v1/resource
// with the payload of title=&description=a

// Response:
// 422 Unprocessable Entity
{
    "error": {
        "code": 422,
        "message": {
            "title": [
                "The title field is required."
            ],
            "description": [
                "The description must be at least 2 characters."
            ]
        }
    }
}
```

**Comment by appkr** [comment]
API changed. As of 0.1.18 you should chain `setMeta(['foo' => 'bar'])` method, instead of passing the append data as an argument.
