### ISSUE TITLE
Documentation still not cool

### ISSUE THREAD

**Issue by tekkenking** [appkr/fractal#3]
I'll suggest you redo the documentation for this awesome package... You'll get more people to use the package.

**Comment by appkr** [comment]
Thanks for the kind word. I'd like to welcome your opinion on which point of documentation should I elaborate more. I'll redo the documentation anyway as soon as possible.

**Comment by MartijnThomas** [comment]
I'm not saying that the docs are bad but what is missing is a simple example implementation for Laravel, without having to dig in the example files.

Just add something like this to the docs:

    use App\User;
    use Appkr\Fractal\Http\Response;
    use App\Http\Controllers\Controller;
    use App\Transformers\UserTransformer;

    class UserController extends Controller
    {

        public function __construct(Response $response)
        {
            $this->response = $response;
        }

        /**
         * Display a listing of the resource.
         *
         * @return Response
         */
        public function index()
        {
            return $this->response->withPagination(
                User::latest()->paginate(25),
                new UserTransformer,
                'sites'
            );
        }
    }

This will show the user immediately how to incorporate it in his/her project.

**Comment by appkr** [comment]
@tekkenking Thanks man. Your recommendation was reflected just before.
